### ISSUE TITLE
Question: partly GPU inference?

### ISSUE THREAD

**Issue by mvsoom** [Maknee/minigpt4.cpp#15]
Is it possible to offload some of the computation (on the LLM) side to the GPU? As with llama.cpp?

**Comment by Maknee** [comment]
Yes. It should be possible. For the language model (vicuna), you can edit these flags in cmake to enable GPU offloading (like cublas)

[CMakeLists.txt](https://github.com/ggerganov/llama.cpp/blob/master/CMakeLists.txt#L67)

**Comment by mvsoom** [comment]
Great! Thank you!

**Comment by deadpipe** [comment]
> Yes. It should be possible. For the language model (vicuna), you can edit these flags in cmake to enable GPU offloading (like cublas)
> 
> [CMakeLists.txt](https://github.com/ggerganov/llama.cpp/blob/master/CMakeLists.txt#L67)

@Maknee 

I tried setting option(MINIGPT4_CUBLAS  "minigpt4: use cuBLAS" ON) in the [CMakeLists.txt](https://github.com/Maknee/minigpt4.cpp/blob/master/CMakeLists.txt#L35).

But when i run cmake --build . --config Release, 

i get this error below unfortunately : - 

![image](https://github.com/Maknee/minigpt4.cpp/assets/142412134/89c709a6-7086-436d-8b59-8dc8da4f14b8)

Any advice to deal with is highly appreciated
