### ISSUE TITLE
gradio errors 'scale should be integer' and 'button object ha no attribute style'

### ISSUE THREAD

**Issue by FilRav** [Maknee/minigpt4.cpp#22]
Following [https://github.com/OpenTalker/SadTalker/issues/693#issuecomment-1789530148](url) I uninstalled gradio 4.7.1 and installed version 3.41.2.

```
python3 -m pip uninstall gradio
python3 -m pip install gradio=3.41.2
```

**Comment by deadpipe** [comment]
Use older version of Gradio, that work fine
for me it is 3.36.1

**Comment by Maknee** [comment]
Thank you! I'll update requirements.txt to reflect this older version of gradio.
