### ISSUE TITLE
Files uploaded to minigpt4-7b-ggml and minigpt4-13b-ggml HF repositories are the same

### ISSUE THREAD

**Issue by felladrin** [Maknee/minigpt4.cpp#9]
I noticed that the files uploaded to [maknee/minigpt4-7b-ggml](https://huggingface.co/datasets/maknee/minigpt4-7b-ggml) are actually the same that were uploaded to [maknee/minigpt4-13b-ggml](https://huggingface.co/datasets/maknee/minigpt4-13b-ggml).

Also confirmed by running the model. It identifies `minigpt4-7b-ggml` with `Model type: Vicuna13B`.

<img width="629" alt="image" src="https://github.com/Maknee/minigpt4.cpp/assets/418083/645aa565-8526-450f-ae28-39fd4ce5c0bc">

**Comment by Maknee** [comment]
Wow, I didn't even realize this... Thanks for the catch! Probably pointed the 7B to the remote 13B folder when uploading...

I will convert 7B and upload the results. Will update when that is done.

**Comment by Maknee** [comment]
Updated. It should show up as 7B model now.
